name: Unit 8 – Alerts + Prompts
autograding:
  tests:
    - name: convertTemp() exact prompt + alert with 212°F -> 100.00°C
      setup: echo "No setup needed"
      run: >
        node -e "
          global.__prompts = [];
          global.prompt = (msg) => { global.__prompts.push(String(msg)); return '212'; };
          global.__alerts = [];
          global.alert  = (msg) => { global.__alerts.push(String(msg)); };

          const fs = require('fs');
          const vm = require('vm');
          global.window = global;
          const code = fs.readFileSync('script.js', 'utf8');
          vm.runInThisContext(code, { filename: 'script.js' });

          if (typeof convertTemp !== 'function') {
            console.error('convertTemp() not found on global scope');
            process.exit(1);
          }
          convertTemp();

          const expectedPrompt = 'Enter temperature in Fahrenheit';
          const expectedAlert  = 'Temperature in Celsius: 100.00';

          if (!global.__prompts.includes(expectedPrompt)) {
            console.error('Expected prompt:', expectedPrompt, 'got:', global.__prompts);
            process.exit(1);
          }
          if (!global.__alerts.includes(expectedAlert)) {
            console.error('Expected alert:', expectedAlert, 'got:', global.__alerts);
            process.exit(1);
          }
        "
      timeout: 20
      points: 50

    - name: circleArea() exact prompt + alert with r=5 -> 78.54
      run: >
        node -e "
          global.__prompts = [];
          global.prompt = (msg) => { global.__prompts.push(String(msg)); return '5'; };
          global.__alerts = [];
          global.alert  = (msg) => { global.__alerts.push(String(msg)); };

          const fs = require('fs');
          const vm = require('vm');
          global.window = global;
          const code = fs.readFileSync('script.js', 'utf8');
          vm.runInThisContext(code, { filename: 'script.js' });

          if (typeof circleArea !== 'function') {
            console.error('circleArea() not found on global scope');
            process.exit(1);
          }
          circleArea();

          const expectedPrompt = 'Enter circle radius';
          const expectedAlert  = 'Area of the circle: 78.54';

          if (!global.__prompts.includes(expectedPrompt)) {
            console.error('Expected prompt:', expectedPrompt, 'got:', global.__prompts);
            process.exit(1);
          }
          if (!global.__alerts.includes(expectedAlert)) {
            console.error('Expected alert:', expectedAlert, 'got:', global.__alerts);
            process.exit(1);
          }
        "
      timeout: 20
      points: 50
