name: Unit 8 – Alerts + Prompts
autograding:
  tests:
    - name: convertTemp() exact prompt + alert with 212°F -> 100.00°C
      setup: echo "No setup needed"
      run: >
        node -e "
          // stub prompt/alert
          global.__prompts=[];
          global.prompt=(msg)=>{ global.__prompts.push(String(msg)); return '212'; };
          global.__alerts=[];
          global.alert=(msg)=>{ global.__alerts.push(String(msg)); };

          // require student code and call function
          const mod = require('./script.js');
          const f = mod && mod.convertTemp;
          if (typeof f !== 'function') { console.error('convertTemp() not found'); process.exit(1); }
          f();

          // verify prompt text
          const expectedPrompt = 'Enter temperature in Fahrenheit';
          if (!global.__prompts.includes(expectedPrompt)) {
            console.error('Expected prompt:', expectedPrompt, 'but saw:', global.__prompts);
            process.exit(1);
          }

          // verify alert text
          const expectedAlert = 'Temperature in Celsius: 100.00';
          if (!global.__alerts.includes(expectedAlert)) {
            console.error('Expected alert:', expectedAlert, 'but saw:', global.__alerts);
            process.exit(1);
          }
        "
      timeout: 20
      points: 50

    - name: circleArea() exact prompt + alert with r=5 -> 78.54
      run: >
        node -e "
          // stub prompt/alert
          global.__prompts=[];
          global.prompt=(msg)=>{ global.__prompts.push(String(msg)); return '5'; };
          global.__alerts=[];
          global.alert=(msg)=>{ global.__alerts.push(String(msg)); };

          // require student code and call function
          const mod = require('./script.js');
          const f = mod && mod.circleArea;
          if (typeof f !== 'function') { console.error('circleArea() not found'); process.exit(1); }
          f();

          // verify prompt text
          const expectedPrompt = 'Enter circle radius';
          if (!global.__prompts.includes(expectedPrompt)) {
            console.error('Expected prompt:', expectedPrompt, 'but saw:', global.__prompts);
            process.exit(1);
          }

          // verify alert text
          const expectedAlert = 'Area of the circle: 78.54';
          if (!global.__alerts.includes(expectedAlert)) {
            console.error('Expected alert:', expectedAlert, 'but saw:', global.__alerts);
            process.exit(1);
          }
        "
      timeout: 20
      points: 50
